auth0-samples/auth0-angular-samples

- 01-Login/src/app/auth/auth0-variables.ts.example
- 02-Custom-Login/src/app/auth/auth0-variables.ts.example
- 03-User-Sessions/src/app/auth/auth0-variables.ts.example
- 04-Calling-API/src/app/auth/auth0-variables.ts.example
- 05-Authorization/src/app/auth/auth0-variables.ts.example
This commit fixes code errors in sample configuration files
removing linter errors and compile time errors.
Thanks!
> Fix code syntax errors in sample variable configs

- 03-User-Sessions/package.json
Be consistent.
Thanks to @Amialc!
> Use the same version of auth0-js in all samples. Fixes #6

- 00-Hosted-Login/package.json
If you agree on this PR, I think it might be a good idea to not merge this until #20 is merged.
That way I can ensure tests are still working on v4.
I'd be happy to update the other samples as well (using separate PR's or this one as you prefer).
> chore(00-HostedLogin): update to angular v4.0.0

- 01-Embedded-Login/README.md
Updated readme to add missing step of switching to the embedded-login branch and made the directions more clear.
> Updated readme to add missing step

- 01-Login/src/app/auth/auth.service.ts
The callback URL should refer to the source of truth.
> Update callback url.

- 01-Login/package.json
- 01-Login/src/app/auth/auth.service.ts
Reverts auth0-samples/auth0-angular-samples#59
> Revert "Use "@types/auth0-js""

- README.md
Update package `auth0.js` and `lock` package versions.
> Update package versions in the README file

- 01-Login/src/polyfills.ts
CasperJS doesn't work without this pollyfills
> Use pollyfills for casperjs to work

- 06-Single-Sign-On/sso-app-one/src/app/auth/auth.service.ts
update auth0.service.ts in 06-Single-Sign-On/sso-app-one to use checkSession instead of renewAuth
>  Update auth0.service.ts to use checkSession

- 01-Login/.angular-cli.json
- 02-User-Profile/.angular-cli.json
- 03-Calling-an-API/.angular-cli.json
- 04-Authorization/.angular-cli.json
- 05-Token-Renewal/.angular-cli.json
- 06-Single-Sign-On/sso-app-one/.angular-cli.json
- 06-Single-Sign-On/sso-app-two/.angular-cli.json
This is resubmitted #93
This dates to old version of CLI and its documentation. The current one
ships the corrected configuration:
https://git.io/vxBUw
Thanks!
> Fix wrong order of CSS files inclusion

- 01-Login/src/app/auth/auth.service.ts
- 02-User-Profile/src/app/auth/auth.service.ts
- 03-Calling-an-API/src/app/auth/auth.service.ts
- 04-Authorization/src/app/auth/auth.service.ts
- 05-Token-Renewal/src/app/auth/auth.service.ts
- 06-Single-Sign-On/sso-app-one/src/app/auth/auth.service.ts
- 06-Single-Sign-On/sso-app-two/src/app/auth/auth.service.ts
Clear session at Auth0 authorization server calling `/v2/logout` endpoint when perform logout.
> Logout from Auth0 authorization server

- 01-Login/src/app/auth/auth.service.ts
- 02-User-Profile/src/app/auth/auth.service.ts
- 03-Calling-an-API/src/app/auth/auth.service.ts
- 04-Authorization/src/app/auth/auth.service.ts
- 05-Token-Renewal/src/app/auth/auth.service.ts
- 06-Single-Sign-On/sso-app-one/src/app/auth/auth.service.ts
- 06-Single-Sign-On/sso-app-two/src/app/auth/auth.service.ts
Incorrect return to parameter for log out endpoint fixed
> Incorrect return to parameter for log out endpoint fixed

- 01-Login/angular.json
- 01-Login/package.json
- 01-Login/src/app/app.component.html
- 01-Login/src/app/components/footer/footer.component.html
- 01-Login/src/app/components/hero/hero.component.html
- 01-Login/src/app/components/home-content/home-content.component.html
- 01-Login/src/app/components/nav-bar/nav-bar.component.html
- 01-Login/src/app/components/nav-bar/nav-bar.component.ts
- 01-Login/src/app/containers/profile/profile.component.html
- 01-Login/src/index.html
- 02-Calling-an-API/angular.json
- 02-Calling-an-API/package.json
- 02-Calling-an-API/src/app/app.component.html
- 02-Calling-an-API/src/app/components/footer/footer.component.html
- 02-Calling-an-API/src/app/components/hero/hero.component.html
- 02-Calling-an-API/src/app/components/home-content/home-content.component.html
- 02-Calling-an-API/src/app/components/nav-bar/nav-bar.component.html
- 02-Calling-an-API/src/app/components/nav-bar/nav-bar.component.ts
- 02-Calling-an-API/src/app/containers/external-api/external-api.component.css
- 02-Calling-an-API/src/app/containers/external-api/external-api.component.html
- 02-Calling-an-API/src/app/containers/profile/profile.component.html
- 02-Calling-an-API/src/index.html
* Various classes added that make the sample look more consistant using only Bootstrap vs. Bootstrap + our theme
* Included Bootstrap as a dependency (in preparation for https://github.com/auth0-quickstarts/samples-bootstrap-theme/issues/2)
> Updates to the quickstart theme

- 01-Login/angular.json
- 01-Login/package.json
- 01-Login/src/index.html
- 02-Calling-an-API/angular.json
- 02-Calling-an-API/package.json
- 02-Calling-an-API/src/index.html
In preparation for https://github.com/auth0-quickstarts/samples-bootstrap-theme/pull/4
> Replaced theme package with theme CDN URL

- Sample-01/README.md
Hi, I updated some of the links that were returning a 404. The problem seems to be related to the docs.auth0.com domains which couldn't be resolved.
Please ignore this PR if the links were correct.
cc @anacidre @samjulien
> docs: update dead links

- README.md
> Update Readme to include Auth0 configuration explanation

- Sample-01/package-lock.json
- Sample-01/package.json
Switch to `copyfiles`, so script `copy:server` works x-platform.
I didn't include the `package-lock.json`, to prevent unwanted changes in resolution of content.
Let me know if I should include the file,
Thanks!
> Fix `postbuild` step failing on Windows OS

- Sample-01/src/app/app.module.ts
When using the sample project I noticed the code highlighting did not work and was throwing console issues, did some googling, found a fix, throwing here if you want it.
**Before**
**After**
> Fixes the code language highlighting

- .github/actions/build/action.yml
- .github/actions/test/action.yml
- .github/workflows/e2e-test.yml
- .github/workflows/test.yml
Adds workflows to run Build, Unit Tests and E2E Tests in GitHub Actions.
Will remove the Circle CI config file in a follow up PR.
> Add GitHub Actions

- Sample-01/src/app/pages/error/error.component.ts
- Standalone/src/app/pages/error/error.component.ts
Samples werent compiling due to one of the latest updates
> Ensure samples compile as expected
