auth0-samples/auth0-angular-samples

- README.md
This notice and an documentation link should help users
to fix problems when using sammples with accounts that have not
yet been migrated to new API authorization flows.
See my case:
auth0-samples/auth0-angular-samples#4
and support forum ticket:
https://auth0.com/forum/t/unsupported-response-type-token-id-token/4919
Thanks!
> :memo: Add notice about new API authorization flows

- 00-Hosted-Login/src/app/app.component.spec.ts
- 00-Hosted-Login/src/app/auth/auth.service.spec.ts
- 00-Hosted-Login/src/app/home/home.component.spec.ts
- 00-Hosted-Login/src/test.ts
Fixes #19
This had several reasons of failing:
- polyfills.ts was executed twice when running `npm run test`
- multiple dependencies could not be resolved on a per test base
- invalid tests (angular-cli default tests were still there).
I'm not sure if you guys want to have tests. If not, I can drop this PR and remove them instead. But if tests are preferred, this should allow people to execute them.
> fix(00-HostedLogin): fix tests

- 05-Token-Renewal/README.md
- 05-Token-Renewal/src/app/auth/auth.service.ts
This PR will have a corresponding one in the auth0/docs repo to also fix the issue in the sample snippets.
> Fix token renewal by explicitly setting postMessageOrigin in renewAuth

- 01-Login/package.json
Fixes an issue where a change in an Angular CLI v1.7.2 dependency, `AutoPrefixer`, causes the error: 
> BrowserslistError: Unknown browser query `dead`
`@angular/cli@1.7.4` has a dependency on `autoprefixer@7.2.6` which has a dependency on `browserslist@2.11.3`. `browserslist` < 3.0 triggers the error when latest version of Bootstrap to date, `bootstrap@4.1.2`, is used. 
Change to `"bootstrap": "^3.3.7"` to match the `bootstrap` version of all other steps.
> Change bootstrap dependency to version ^3.3.7

- 01-Embedded-Login/README.md
The phrase 'Custom Domains' is repeated and feels out of place when reading the readme.
> Remove redundant 'Custom Domains'

- 05-Token-Renewal/src/app/auth/auth.service.ts
- 05-Token-Renewal/src/app/home/home.component.ts
Get token expiration from `AuthService` property instead of localStorage.
> Properly get token expiration

- 01-Login/src/app/app.component.ts
- 01-Login/src/app/auth/auth.service.ts
- 02-User-Profile/src/app/app.component.ts
- 02-User-Profile/src/app/auth/auth.service.ts
- 03-Calling-an-API/src/app/app.component.ts
- 03-Calling-an-API/src/app/auth/auth.service.ts
- 04-Authorization/src/app/app.component.ts
- 04-Authorization/src/app/auth/auth.service.ts
- 05-Token-Renewal/src/app/app.component.ts
- 05-Token-Renewal/src/app/auth/auth.service.ts
- 06-Single-Sign-On/sso-app-one/src/app/auth/auth.service.ts
- 06-Single-Sign-On/sso-app-two/src/app/auth/auth.service.ts
- Instead of storing a flag on the localstorage, use a method that checks for variable in-memory value presence. 
- Replace usage of `new Date().getTime()` with `Date.now()`.
> Stop using localstorage to keep logged in state

- 02-Calling-an-API/Dockerfile
Hello, see issue #179 
I did some digging and found that the `COPY` was copying the files into `./dist/` and was not creating a `./dist/login-demo`.  For example, after a docker build, the index.html was available at `./dist/index.html` but the server was trying to serve it from `./dist/login-demo/index.html`, hence the 404.
This fix will allow the Docker instructions in the README for sample 02 to work as expected.  After applying, localhost:3000 started serving the sample app to me as expected.
> Copy build output to login-demo directory expected by npm server

- 01-Login/src/app/auth/auth.service.ts
When the target contains route parameters and we use the `navigate` method of the Angular router the route parameters get encoded which will result in an invalid url. We should use `navigateByUrl` here instead.
> Fix broken redirects

- 01-Login/src/app/auth/auth.guard.ts
- 01-Login/src/app/auth/auth.service.ts
- 02-Calling-an-API/src/app/auth/auth.guard.ts
- 02-Calling-an-API/src/app/auth/auth.service.ts
While the post login redirect works in the example, it breaks as soon as all routes (including the one to the HomeComponent) are restricted by the AuthGuard. 
In this case you will always be redirected to "domain.com/" after logging in even if you opened the browser at "domain.com/profile".
I thought this might be useful since this example is also used in the [Auth0 Quickstart for Angular here](https://manage.auth0.com/dashboard/eu/oo-vouchers-local/applications/47ntxdQlfLAYG00bf65OHyoNDy4ckauW/quickstart).
> fixed auth redirects

- Sample-01/auth_config.json.example
- Sample-01/src/app/app-routing.module.ts
- Sample-01/src/app/app.module.ts
- Sample-01/src/app/pages/error/error.component.html
- Sample-01/src/app/pages/error/error.component.ts
- Sample-01/src/app/pages/external-api/external-api.component.html
- Sample-01/src/app/pages/external-api/external-api.component.ts
- Sample-01/src/environments/environment.prod.ts
- Sample-01/src/environments/environment.ts
This PR improves error handling in two areas:
- `/authorize` errors that are sent back to the redirect_uri (e.g. Audience misconfiguration errors)
- API errors (mostly API not running)
Closes #227
> Improve error handling for the user

- Sample-01/api-server.js
- Sample-01/src/app/pages/external-api/external-api.component.html
- Sample-01/src/app/pages/external-api/external-api.component.ts
- Sample-01/src/environments/environment.prod.ts
- Sample-01/src/environments/environment.ts
This PR attempts to make it work in more scenarios where the audience configuration value has not been specified or has been left at the default value of YOUR_API_IDENTIFIER (you might get this if you use the "download sample" tool on the quickstart but do not have any valid APIs set up in your tenant).
To do this:
- The API server gracefully exits if there's not a valid audience, with a warning message
- When Audience is missing or set to `YOUR_API_IDENTIFIER`, the sample disables the "Ping API" button and displays some help content (see below) to try and aid the developer in setting up the audience and what it means
**When no audience set:**
**When an audience is set:**
Closes #226
> Make sample more resilient when handling missing or default audience

- Sample-01/package-lock.json
- Sample-01/package.json
This PR downgrades Fontawesome for Angular, as the sample is using Angular 11 and the current version has been incorrectly updated as only 0.8.x works with Angular 11.
Also bumped our own SDK.
> Downgrade fontawesome

- .github/ISSUE_TEMPLATE/Bug Report.yml
- .github/ISSUE_TEMPLATE/Feature Request.yml
- .github/ISSUE_TEMPLATE/config.yml
This PR adds issue forms for **feature requests** and **bug reports**. This repository does not currently have any issue templates, so none was removed.
> Add issue forms [SDK-4312]

- .circleci/config.yml
Chromedriver for Chrome 115 or newer is unable to install because of a change in the API that stores the information, `circleci/browser-tools@1.4.3` includes the fix for this so the chromedriver installs should now work again.
Also updates the other orbs used, once verified fully here will roll out to any other repos as necessary.
> Update to latest browser-tools orb to fix chromedriver issue

- .github/dependabot.yml
Given that `@angular` updates need to be performed together, create a group that instructs dependabot to do this, [docs here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups)
> Group angular updates

- .circleci/config.yml
There were some further changes to browser-tools that are required, it seems that potentially the new version of chrome is exposing the issues these fixed
See auth0-samples/auth0-ionic-samples/pull/621
> Update to latest browser-tools orb

- Sample-01/api-server.js
- Standalone/api-server.js
> Update api-server.js to include the hardcoded audience placeholder

- README.md
- netlify.toml
Added netlify.toml to simplify the deployment of this QS as a Netlify website.
> added netlify.toml

- README.md
- Sample-01/api-server.js
- Sample-01/src/app/pages/external-api/external-api.component.html
- Sample-01/src/environments/environment.prod.ts
- Sample-01/src/environments/environment.ts
- Standalone/api-server.js
- Standalone/src/app/pages/external-api/external-api.component.html
- Standalone/src/environments/environment.prod.ts
- Standalone/src/environments/environment.ts
- Replaced all usage of  `"YOUR_API_IDENTIFIER"` -> `"{yourApiIdentifier}"`. Currently, if a user downloads the Auth0 Angular sample app without an API, the downloaded sample app has its `audience` value in auth_config.json set to 
`"{yourApiIdentifier}"`. This is because `"YOUR_API_IDENTIFIER"` is no longer the default value, as it has been swapped with `"{yourApiIdentifier}"`.
- https://github.com/auth0-samples/auth0-angular-samples/issues/466
- https://github.com/auth0-samples/auth0-angular-samples/issues/226
> Updating default audience config values and logic

- Sample-01/api-server.js
- Standalone/api-server.js
Currently, this line in api-server.js is:
```
['{yourApiIdentifier}', '{API_IDENTIFIER}'].includes(
authConfig.authorizationParams.audience
)
```
But when the Angular sample app is downloaded from the Quickstarts (both Dashboard and from auth0.com/docs) and the user does not have an API created, this line in api-server.js becomes: 
```
['{yourApiIdentifier}', '{yourApiIdentifier}'].includes(
authConfig.authorizationParams.audience
```
This is because `'{API_IDENTIFIER}'` is being replaced with `'{yourApiIdentifier}'` when downloaded as a sample app. 
**Note:** this was happening even prior to the changes made in https://github.com/auth0-samples/auth0-angular-samples/pull/524, so that PR did not create this text replacing.
In this PR, we changed `['{yourApiIdentifier}', …
> Changing duplicate {yourApiIdentifier} value when downloaded as sample app
